spring:
  application:
    name: ms-redis-lettuce
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10000
  lettuce:
    pool:
      maxActive: 8
      maxWait: 10000
      maxIdle: 8
      minIdle: 0
    shutdownTimeout: 100

server:
  port: 18510

logging:
  level:
    org:
      springframework: debug